


export const userConstants = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT: "LOGOUT",

    AVATAR_UPDATE_TO_STATE: "AVATAR_UPDATE_TO_STATE",
    AVATAR_UPDATE_REQUEST: "AVATAR_UPDATE_REQUEST",
    AVATAR_UPDATE_SUCCESS: "AVATAR_UPDATE_SUCCESS",
    AVATAR_UPDATE_FAILURE: "AVATAR_UPDATE_FAILURE",

    UPDATE_REQUEST: "AVATAR_UPDATE_REQUEST",
    UPDATE_SUCCESS: "AVATAR_UPDATE_SUCCESS",
    UPDATE_FAILURE: "AVATAR_UPDATE_FAILURE"


};

